/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimesheetRouteImport } from './routes/_app/timesheet'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppLeaveWfhRouteImport } from './routes/_app/leave-wfh'
import { Route as AppHelpdeskRouteImport } from './routes/_app/helpdesk'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppEmsRouteImport } from './routes/_app/ems'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppLeaveWfhIndexRouteImport } from './routes/_app/leave-wfh.index'
import { Route as AppEmsIndexRouteImport } from './routes/_app/ems.index'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app/attendance.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as AppLeaveWfhMonitorRouteImport } from './routes/_app/leave-wfh.monitor'
import { Route as AppLeaveWfhHolidaysRouteImport } from './routes/_app/leave-wfh.holidays'
import { Route as AppLeaveWfhApprovalsRouteImport } from './routes/_app/leave-wfh.approvals'
import { Route as AppLeaveWfhApplyWfhRouteImport } from './routes/_app/leave-wfh.apply-wfh'
import { Route as AppLeaveWfhApplyLeaveRouteImport } from './routes/_app/leave-wfh.apply-leave'
import { Route as AppEmsRequestsRouteImport } from './routes/_app/ems.requests'
import { Route as AppEmsProfileRouteImport } from './routes/_app/ems.profile'
import { Route as AppEmsPoliciesRouteImport } from './routes/_app/ems.policies'
import { Route as AppEmsLettersRouteImport } from './routes/_app/ems.letters'
import { Route as AppEmsDocumentsRouteImport } from './routes/_app/ems.documents'
import { Route as AppEmsApprovalsRouteImport } from './routes/_app/ems.approvals'
import { Route as AppEmsAdminRouteImport } from './routes/_app/ems.admin'
import { Route as AppEmployeesIdRouteImport } from './routes/_app/employees.$id'
import { Route as AppAttendanceExceptionsRouteImport } from './routes/_app/attendance.exceptions'
import { Route as AppAttendanceCalendarRouteImport } from './routes/_app/attendance.calendar'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimesheetRoute = AppTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveWfhRoute = AppLeaveWfhRouteImport.update({
  id: '/leave-wfh',
  path: '/leave-wfh',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpdeskRoute = AppHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmsRoute = AppEmsRouteImport.update({
  id: '/ems',
  path: '/ems',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveWfhIndexRoute = AppLeaveWfhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeaveWfhRoute,
} as any)
const AppEmsIndexRoute = AppEmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppLeaveWfhMonitorRoute = AppLeaveWfhMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppLeaveWfhRoute,
} as any)
const AppLeaveWfhHolidaysRoute = AppLeaveWfhHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AppLeaveWfhRoute,
} as any)
const AppLeaveWfhApprovalsRoute = AppLeaveWfhApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppLeaveWfhRoute,
} as any)
const AppLeaveWfhApplyWfhRoute = AppLeaveWfhApplyWfhRouteImport.update({
  id: '/apply-wfh',
  path: '/apply-wfh',
  getParentRoute: () => AppLeaveWfhRoute,
} as any)
const AppLeaveWfhApplyLeaveRoute = AppLeaveWfhApplyLeaveRouteImport.update({
  id: '/apply-leave',
  path: '/apply-leave',
  getParentRoute: () => AppLeaveWfhRoute,
} as any)
const AppEmsRequestsRoute = AppEmsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppEmsProfileRoute = AppEmsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppEmsPoliciesRoute = AppEmsPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppEmsLettersRoute = AppEmsLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppEmsDocumentsRoute = AppEmsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppEmsApprovalsRoute = AppEmsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppEmsAdminRoute = AppEmsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppEmsRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)
const AppAttendanceExceptionsRoute = AppAttendanceExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceCalendarRoute = AppAttendanceCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppAttendanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/ems': typeof AppEmsRouteWithChildren
  '/expenses': typeof AppExpensesRoute
  '/helpdesk': typeof AppHelpdeskRoute
  '/leave-wfh': typeof AppLeaveWfhRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/timesheet': typeof AppTimesheetRoute
  '/attendance/calendar': typeof AppAttendanceCalendarRoute
  '/attendance/exceptions': typeof AppAttendanceExceptionsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/ems/admin': typeof AppEmsAdminRoute
  '/ems/approvals': typeof AppEmsApprovalsRoute
  '/ems/documents': typeof AppEmsDocumentsRoute
  '/ems/letters': typeof AppEmsLettersRoute
  '/ems/policies': typeof AppEmsPoliciesRoute
  '/ems/profile': typeof AppEmsProfileRoute
  '/ems/requests': typeof AppEmsRequestsRoute
  '/leave-wfh/apply-leave': typeof AppLeaveWfhApplyLeaveRoute
  '/leave-wfh/apply-wfh': typeof AppLeaveWfhApplyWfhRoute
  '/leave-wfh/approvals': typeof AppLeaveWfhApprovalsRoute
  '/leave-wfh/holidays': typeof AppLeaveWfhHolidaysRoute
  '/leave-wfh/monitor': typeof AppLeaveWfhMonitorRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/attendance/': typeof AppAttendanceIndexRoute
  '/ems/': typeof AppEmsIndexRoute
  '/leave-wfh/': typeof AppLeaveWfhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/assets': typeof AppAssetsRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/expenses': typeof AppExpensesRoute
  '/helpdesk': typeof AppHelpdeskRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/timesheet': typeof AppTimesheetRoute
  '/attendance/calendar': typeof AppAttendanceCalendarRoute
  '/attendance/exceptions': typeof AppAttendanceExceptionsRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/ems/admin': typeof AppEmsAdminRoute
  '/ems/approvals': typeof AppEmsApprovalsRoute
  '/ems/documents': typeof AppEmsDocumentsRoute
  '/ems/letters': typeof AppEmsLettersRoute
  '/ems/policies': typeof AppEmsPoliciesRoute
  '/ems/profile': typeof AppEmsProfileRoute
  '/ems/requests': typeof AppEmsRequestsRoute
  '/leave-wfh/apply-leave': typeof AppLeaveWfhApplyLeaveRoute
  '/leave-wfh/apply-wfh': typeof AppLeaveWfhApplyWfhRoute
  '/leave-wfh/approvals': typeof AppLeaveWfhApprovalsRoute
  '/leave-wfh/holidays': typeof AppLeaveWfhHolidaysRoute
  '/leave-wfh/monitor': typeof AppLeaveWfhMonitorRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/attendance': typeof AppAttendanceIndexRoute
  '/ems': typeof AppEmsIndexRoute
  '/leave-wfh': typeof AppLeaveWfhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/attendance': typeof AppAttendanceRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/ems': typeof AppEmsRouteWithChildren
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/helpdesk': typeof AppHelpdeskRoute
  '/_app/leave-wfh': typeof AppLeaveWfhRouteWithChildren
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/timesheet': typeof AppTimesheetRoute
  '/_app/attendance/calendar': typeof AppAttendanceCalendarRoute
  '/_app/attendance/exceptions': typeof AppAttendanceExceptionsRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/ems/admin': typeof AppEmsAdminRoute
  '/_app/ems/approvals': typeof AppEmsApprovalsRoute
  '/_app/ems/documents': typeof AppEmsDocumentsRoute
  '/_app/ems/letters': typeof AppEmsLettersRoute
  '/_app/ems/policies': typeof AppEmsPoliciesRoute
  '/_app/ems/profile': typeof AppEmsProfileRoute
  '/_app/ems/requests': typeof AppEmsRequestsRoute
  '/_app/leave-wfh/apply-leave': typeof AppLeaveWfhApplyLeaveRoute
  '/_app/leave-wfh/apply-wfh': typeof AppLeaveWfhApplyWfhRoute
  '/_app/leave-wfh/approvals': typeof AppLeaveWfhApprovalsRoute
  '/_app/leave-wfh/holidays': typeof AppLeaveWfhHolidaysRoute
  '/_app/leave-wfh/monitor': typeof AppLeaveWfhMonitorRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
  '/_app/ems/': typeof AppEmsIndexRoute
  '/_app/leave-wfh/': typeof AppLeaveWfhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/assets'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/ems'
    | '/expenses'
    | '/helpdesk'
    | '/leave-wfh'
    | '/projects'
    | '/reports'
    | '/timesheet'
    | '/attendance/calendar'
    | '/attendance/exceptions'
    | '/employees/$id'
    | '/ems/admin'
    | '/ems/approvals'
    | '/ems/documents'
    | '/ems/letters'
    | '/ems/policies'
    | '/ems/profile'
    | '/ems/requests'
    | '/leave-wfh/apply-leave'
    | '/leave-wfh/apply-wfh'
    | '/leave-wfh/approvals'
    | '/leave-wfh/holidays'
    | '/leave-wfh/monitor'
    | '/projects/$id'
    | '/attendance/'
    | '/ems/'
    | '/leave-wfh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/assets'
    | '/dashboard'
    | '/employees'
    | '/expenses'
    | '/helpdesk'
    | '/projects'
    | '/reports'
    | '/timesheet'
    | '/attendance/calendar'
    | '/attendance/exceptions'
    | '/employees/$id'
    | '/ems/admin'
    | '/ems/approvals'
    | '/ems/documents'
    | '/ems/letters'
    | '/ems/policies'
    | '/ems/profile'
    | '/ems/requests'
    | '/leave-wfh/apply-leave'
    | '/leave-wfh/apply-wfh'
    | '/leave-wfh/approvals'
    | '/leave-wfh/holidays'
    | '/leave-wfh/monitor'
    | '/projects/$id'
    | '/attendance'
    | '/ems'
    | '/leave-wfh'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/_app/assets'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/ems'
    | '/_app/expenses'
    | '/_app/helpdesk'
    | '/_app/leave-wfh'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/timesheet'
    | '/_app/attendance/calendar'
    | '/_app/attendance/exceptions'
    | '/_app/employees/$id'
    | '/_app/ems/admin'
    | '/_app/ems/approvals'
    | '/_app/ems/documents'
    | '/_app/ems/letters'
    | '/_app/ems/policies'
    | '/_app/ems/profile'
    | '/_app/ems/requests'
    | '/_app/leave-wfh/apply-leave'
    | '/_app/leave-wfh/apply-wfh'
    | '/_app/leave-wfh/approvals'
    | '/_app/leave-wfh/holidays'
    | '/_app/leave-wfh/monitor'
    | '/_app/projects/$id'
    | '/_app/attendance/'
    | '/_app/ems/'
    | '/_app/leave-wfh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timesheet': {
      id: '/_app/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof AppTimesheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-wfh': {
      id: '/_app/leave-wfh'
      path: '/leave-wfh'
      fullPath: '/leave-wfh'
      preLoaderRoute: typeof AppLeaveWfhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/helpdesk': {
      id: '/_app/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof AppHelpdeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ems': {
      id: '/_app/ems'
      path: '/ems'
      fullPath: '/ems'
      preLoaderRoute: typeof AppEmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-wfh/': {
      id: '/_app/leave-wfh/'
      path: '/'
      fullPath: '/leave-wfh/'
      preLoaderRoute: typeof AppLeaveWfhIndexRouteImport
      parentRoute: typeof AppLeaveWfhRoute
    }
    '/_app/ems/': {
      id: '/_app/ems/'
      path: '/'
      fullPath: '/ems/'
      preLoaderRoute: typeof AppEmsIndexRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/leave-wfh/monitor': {
      id: '/_app/leave-wfh/monitor'
      path: '/monitor'
      fullPath: '/leave-wfh/monitor'
      preLoaderRoute: typeof AppLeaveWfhMonitorRouteImport
      parentRoute: typeof AppLeaveWfhRoute
    }
    '/_app/leave-wfh/holidays': {
      id: '/_app/leave-wfh/holidays'
      path: '/holidays'
      fullPath: '/leave-wfh/holidays'
      preLoaderRoute: typeof AppLeaveWfhHolidaysRouteImport
      parentRoute: typeof AppLeaveWfhRoute
    }
    '/_app/leave-wfh/approvals': {
      id: '/_app/leave-wfh/approvals'
      path: '/approvals'
      fullPath: '/leave-wfh/approvals'
      preLoaderRoute: typeof AppLeaveWfhApprovalsRouteImport
      parentRoute: typeof AppLeaveWfhRoute
    }
    '/_app/leave-wfh/apply-wfh': {
      id: '/_app/leave-wfh/apply-wfh'
      path: '/apply-wfh'
      fullPath: '/leave-wfh/apply-wfh'
      preLoaderRoute: typeof AppLeaveWfhApplyWfhRouteImport
      parentRoute: typeof AppLeaveWfhRoute
    }
    '/_app/leave-wfh/apply-leave': {
      id: '/_app/leave-wfh/apply-leave'
      path: '/apply-leave'
      fullPath: '/leave-wfh/apply-leave'
      preLoaderRoute: typeof AppLeaveWfhApplyLeaveRouteImport
      parentRoute: typeof AppLeaveWfhRoute
    }
    '/_app/ems/requests': {
      id: '/_app/ems/requests'
      path: '/requests'
      fullPath: '/ems/requests'
      preLoaderRoute: typeof AppEmsRequestsRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/ems/profile': {
      id: '/_app/ems/profile'
      path: '/profile'
      fullPath: '/ems/profile'
      preLoaderRoute: typeof AppEmsProfileRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/ems/policies': {
      id: '/_app/ems/policies'
      path: '/policies'
      fullPath: '/ems/policies'
      preLoaderRoute: typeof AppEmsPoliciesRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/ems/letters': {
      id: '/_app/ems/letters'
      path: '/letters'
      fullPath: '/ems/letters'
      preLoaderRoute: typeof AppEmsLettersRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/ems/documents': {
      id: '/_app/ems/documents'
      path: '/documents'
      fullPath: '/ems/documents'
      preLoaderRoute: typeof AppEmsDocumentsRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/ems/approvals': {
      id: '/_app/ems/approvals'
      path: '/approvals'
      fullPath: '/ems/approvals'
      preLoaderRoute: typeof AppEmsApprovalsRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/ems/admin': {
      id: '/_app/ems/admin'
      path: '/admin'
      fullPath: '/ems/admin'
      preLoaderRoute: typeof AppEmsAdminRouteImport
      parentRoute: typeof AppEmsRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
    '/_app/attendance/exceptions': {
      id: '/_app/attendance/exceptions'
      path: '/exceptions'
      fullPath: '/attendance/exceptions'
      preLoaderRoute: typeof AppAttendanceExceptionsRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/calendar': {
      id: '/_app/attendance/calendar'
      path: '/calendar'
      fullPath: '/attendance/calendar'
      preLoaderRoute: typeof AppAttendanceCalendarRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
  }
}

interface AppAttendanceRouteChildren {
  AppAttendanceCalendarRoute: typeof AppAttendanceCalendarRoute
  AppAttendanceExceptionsRoute: typeof AppAttendanceExceptionsRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
}

const AppAttendanceRouteChildren: AppAttendanceRouteChildren = {
  AppAttendanceCalendarRoute: AppAttendanceCalendarRoute,
  AppAttendanceExceptionsRoute: AppAttendanceExceptionsRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
}

const AppAttendanceRouteWithChildren = AppAttendanceRoute._addFileChildren(
  AppAttendanceRouteChildren,
)

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppEmsRouteChildren {
  AppEmsAdminRoute: typeof AppEmsAdminRoute
  AppEmsApprovalsRoute: typeof AppEmsApprovalsRoute
  AppEmsDocumentsRoute: typeof AppEmsDocumentsRoute
  AppEmsLettersRoute: typeof AppEmsLettersRoute
  AppEmsPoliciesRoute: typeof AppEmsPoliciesRoute
  AppEmsProfileRoute: typeof AppEmsProfileRoute
  AppEmsRequestsRoute: typeof AppEmsRequestsRoute
  AppEmsIndexRoute: typeof AppEmsIndexRoute
}

const AppEmsRouteChildren: AppEmsRouteChildren = {
  AppEmsAdminRoute: AppEmsAdminRoute,
  AppEmsApprovalsRoute: AppEmsApprovalsRoute,
  AppEmsDocumentsRoute: AppEmsDocumentsRoute,
  AppEmsLettersRoute: AppEmsLettersRoute,
  AppEmsPoliciesRoute: AppEmsPoliciesRoute,
  AppEmsProfileRoute: AppEmsProfileRoute,
  AppEmsRequestsRoute: AppEmsRequestsRoute,
  AppEmsIndexRoute: AppEmsIndexRoute,
}

const AppEmsRouteWithChildren =
  AppEmsRoute._addFileChildren(AppEmsRouteChildren)

interface AppLeaveWfhRouteChildren {
  AppLeaveWfhApplyLeaveRoute: typeof AppLeaveWfhApplyLeaveRoute
  AppLeaveWfhApplyWfhRoute: typeof AppLeaveWfhApplyWfhRoute
  AppLeaveWfhApprovalsRoute: typeof AppLeaveWfhApprovalsRoute
  AppLeaveWfhHolidaysRoute: typeof AppLeaveWfhHolidaysRoute
  AppLeaveWfhMonitorRoute: typeof AppLeaveWfhMonitorRoute
  AppLeaveWfhIndexRoute: typeof AppLeaveWfhIndexRoute
}

const AppLeaveWfhRouteChildren: AppLeaveWfhRouteChildren = {
  AppLeaveWfhApplyLeaveRoute: AppLeaveWfhApplyLeaveRoute,
  AppLeaveWfhApplyWfhRoute: AppLeaveWfhApplyWfhRoute,
  AppLeaveWfhApprovalsRoute: AppLeaveWfhApprovalsRoute,
  AppLeaveWfhHolidaysRoute: AppLeaveWfhHolidaysRoute,
  AppLeaveWfhMonitorRoute: AppLeaveWfhMonitorRoute,
  AppLeaveWfhIndexRoute: AppLeaveWfhIndexRoute,
}

const AppLeaveWfhRouteWithChildren = AppLeaveWfhRoute._addFileChildren(
  AppLeaveWfhRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppAttendanceRoute: typeof AppAttendanceRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppEmsRoute: typeof AppEmsRouteWithChildren
  AppExpensesRoute: typeof AppExpensesRoute
  AppHelpdeskRoute: typeof AppHelpdeskRoute
  AppLeaveWfhRoute: typeof AppLeaveWfhRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppTimesheetRoute: typeof AppTimesheetRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppAttendanceRoute: AppAttendanceRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppEmsRoute: AppEmsRouteWithChildren,
  AppExpensesRoute: AppExpensesRoute,
  AppHelpdeskRoute: AppHelpdeskRoute,
  AppLeaveWfhRoute: AppLeaveWfhRouteWithChildren,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppTimesheetRoute: AppTimesheetRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
