/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimesheetRouteImport } from './routes/_app/timesheet'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppLeaveWfhRouteImport } from './routes/_app/leave-wfh'
import { Route as AppHelpdeskRouteImport } from './routes/_app/helpdesk'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppEmsRouteImport } from './routes/_app/ems'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppEmployeesIdRouteImport } from './routes/_app/employees.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimesheetRoute = AppTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveWfhRoute = AppLeaveWfhRouteImport.update({
  id: '/leave-wfh',
  path: '/leave-wfh',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpdeskRoute = AppHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEmsRoute = AppEmsRouteImport.update({
  id: '/ems',
  path: '/ems',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/ems': typeof AppEmsRoute
  '/expenses': typeof AppExpensesRoute
  '/helpdesk': typeof AppHelpdeskRoute
  '/leave-wfh': typeof AppLeaveWfhRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/timesheet': typeof AppTimesheetRoute
  '/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRouteWithChildren
  '/ems': typeof AppEmsRoute
  '/expenses': typeof AppExpensesRoute
  '/helpdesk': typeof AppHelpdeskRoute
  '/leave-wfh': typeof AppLeaveWfhRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/timesheet': typeof AppTimesheetRoute
  '/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRouteWithChildren
  '/_app/ems': typeof AppEmsRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/helpdesk': typeof AppHelpdeskRoute
  '/_app/leave-wfh': typeof AppLeaveWfhRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/timesheet': typeof AppTimesheetRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/assets'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/ems'
    | '/expenses'
    | '/helpdesk'
    | '/leave-wfh'
    | '/projects'
    | '/reports'
    | '/timesheet'
    | '/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/assets'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/ems'
    | '/expenses'
    | '/helpdesk'
    | '/leave-wfh'
    | '/projects'
    | '/reports'
    | '/timesheet'
    | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/_app/assets'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/ems'
    | '/_app/expenses'
    | '/_app/helpdesk'
    | '/_app/leave-wfh'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/timesheet'
    | '/_app/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timesheet': {
      id: '/_app/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof AppTimesheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-wfh': {
      id: '/_app/leave-wfh'
      path: '/leave-wfh'
      fullPath: '/leave-wfh'
      preLoaderRoute: typeof AppLeaveWfhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/helpdesk': {
      id: '/_app/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof AppHelpdeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ems': {
      id: '/_app/ems'
      path: '/ems'
      fullPath: '/ems'
      preLoaderRoute: typeof AppEmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppEmsRoute: typeof AppEmsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppHelpdeskRoute: typeof AppHelpdeskRoute
  AppLeaveWfhRoute: typeof AppLeaveWfhRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTimesheetRoute: typeof AppTimesheetRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppEmsRoute: AppEmsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppHelpdeskRoute: AppHelpdeskRoute,
  AppLeaveWfhRoute: AppLeaveWfhRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppTimesheetRoute: AppTimesheetRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
